"""
test_theorem_a_untabulated_omega.py

Checks Theorem 3 (exact support characterization) on sets Omega that do
not appear anywhere in the published Table 1, to guard against the
result having been implicitly tuned to the four tabulated examples.

The support predicted by Theorem 3 (n - 1 in Gamma_Omega, the numerical
semigroup generated by {m - 1 : m in Omega}) is computed here by a
direct breadth-first search over the semigroup -- independent of, and
much more naive than, the Sylvester-Frobenius closed form used in
Corollary 4 -- and compared against the actual zero/nonzero pattern of
the exact enumeration series from mgonal_cactus_series_omega.py.

Reference: F. G. Speyser, "Enumeration and Asymptotic Analysis of Strict
Non-Plane Cactus Graphs over a Finite Set of Cycle Lengths" (in preparation 
for submission to the Journal of Integer Sequences, 2026), Theorem 3.

Author: Frederic G. Speyser
Run: python3 -m pytest test_theorem_a_untabulated_omega.py -v
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import mgonal_cactus_series_omega as om

UNTABULATED_OMEGA = [(7, 11), (5, 9, 13)]
BOUND = 40


def semigroup_support_bfs(omega, bound):
    """n such that n - 1 lies in the numerical semigroup generated by
    {m - 1 : m in omega}, for 1 <= n <= bound, by direct breadth-first
    search -- deliberately not using the Sylvester-Frobenius formula."""
    gens = [m - 1 for m in omega]
    reachable = {0}
    frontier = {0}
    while frontier:
        new_frontier = set()
        for t in frontier:
            for g in gens:
                nt = t + g
                if nt <= bound - 1 and nt not in reachable:
                    reachable.add(nt)
                    new_frontier.add(nt)
        frontier = new_frontier
    return {t + 1 for t in reachable}


def test_theorem_a_on_untabulated_omega():
    for omega in UNTABULATED_OMEGA:
        om.N = BOUND
        s, _ = om.solve_G(omega)
        actual_support = {n for n in range(1, BOUND + 1) if s[n] != 0}
        predicted_support = semigroup_support_bfs(omega, BOUND)
        assert actual_support == predicted_support, (
            f"Omega={omega}: Theorem 3 predicts support {sorted(predicted_support)}, "
            f"actual series support is {sorted(actual_support)}"
        )


if __name__ == "__main__":
    test_theorem_a_on_untabulated_omega()
    print(f"Theorem 3 verified on {len(UNTABULATED_OMEGA)} untabulated Omega: "
          f"{UNTABULATED_OMEGA}")
