"""
test_random_omega_property.py

A property-based (randomized) complement to test_theorem_a_untabulated_omega.py
and test_untabulated_omega_extended.py. Those two files check Theorem 3 (exact
support characterization) on a total of ten Omega chosen by hand -- four
tabulated in the paper's Table 1, six more picked deliberately to cover
specific qualitative combinations (both sizes, both parities, one vs. two
even lengths). Hand-picked test cases are useful for exercising known
qualitative distinctions, but they cannot by themselves rule out a more
subtle bias: since every Omega above was chosen by the same person who
wrote the theorem and the solver, an inadvertent blind spot in one could in
principle be invisible to the other.

This file removes the human from the choice of Omega. It draws a batch of
finite sets uniformly at random -- with a fixed seed, so the run is exactly
reproducible, not a source of flakiness -- and checks Theorem 3 on every one
of them, exactly as the two files above do, but on cases nobody selected for
their qualitative properties. Passing this test is not stronger evidence for
any single Omega than the hand-picked cases already give; it is evidence
against the *specific risk* of unintentional selection bias in what has been
tested so far.

Deliberately excluded: |Omega| = 1 (the single-length case is its own
boundary condition, checked instead by test_boundary_single_length_omega.py
against the companion paper), and the two costly checks (cross-implementation
agreement, numeric critical-pair consistency) that verify_extended_omega.py
already exercises on Omega chosen for other reasons -- this file is meant to
run inside the default, fast `pytest` suite, so it is deliberately restricted
to the cheap check (Theorem 3 support vs. a semigroup BFS) that scales to
dozens of random cases without materially slowing the suite down.

Reference: F. G. Speyser, "Enumeration and Asymptotic Analysis of Strict
Non-Plane Cactus Graphs over a Finite Set of Cycle Lengths" (in preparation
for submission to the Journal of Integer Sequences, 2026), Theorem 3.

Author: Frederic G. Speyser
Run: python3 -m pytest tests/test_random_omega_property.py -v
"""
import sys
import os
import random

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'python'))

import mgonal_cactus_series_omega as om

SEED = 20260826          # fixed, for exact reproducibility -- not a live random run
NUM_RANDOM_OMEGA = 30     # number of random Omega drawn
MIN_LENGTH = 5            # matches the paper's domain Omega subset Z_{>=5}
MAX_LENGTH = 16           # kept modest so the batch runs quickly
MIN_SIZE = 2              # |Omega| = 1 is covered separately (see module docstring)
MAX_SIZE = 4
BOUND = 36                # truncation order for both the series and the BFS


def semigroup_support_bfs(omega, bound):
    """n such that n - 1 lies in the numerical semigroup generated by
    {m - 1 : m in omega}, for 1 <= n <= bound, by direct breadth-first
    search -- independent of, and more naive than, the closed form used
    for two generators in Corollary 4."""
    gens = [m - 1 for m in omega]
    reachable = {0}
    frontier = {0}
    while frontier:
        new_frontier = set()
        for t in frontier:
            for g in gens:
                nt = t + g
                if nt <= bound - 1 and nt not in reachable:
                    reachable.add(nt)
                    new_frontier.add(nt)
        frontier = new_frontier
    return {t + 1 for t in reachable}


def _random_omega_batch():
    rng = random.Random(SEED)
    batch = []
    seen = set()
    while len(batch) < NUM_RANDOM_OMEGA:
        size = rng.randint(MIN_SIZE, MAX_SIZE)
        omega = tuple(sorted(rng.sample(range(MIN_LENGTH, MAX_LENGTH + 1), size)))
        if omega in seen:
            continue
        seen.add(omega)
        batch.append(omega)
    return batch


RANDOM_OMEGA = _random_omega_batch()


def test_theorem3_on_random_omega():
    failures = []
    for omega in RANDOM_OMEGA:
        om.N = BOUND
        s, _ = om.solve_G(omega)
        actual_support = {n for n in range(1, BOUND + 1) if s[n] != 0}
        predicted_support = semigroup_support_bfs(omega, BOUND)
        if actual_support != predicted_support:
            failures.append((omega, sorted(actual_support), sorted(predicted_support)))
    assert not failures, (
        f"Theorem 3 failed on {len(failures)}/{len(RANDOM_OMEGA)} randomly drawn Omega "
        f"(seed={SEED}): {failures}"
    )


if __name__ == "__main__":
    test_theorem3_on_random_omega()
    print(f"Theorem 3 verified on {len(RANDOM_OMEGA)} randomly drawn Omega "
          f"(seed={SEED}): {RANDOM_OMEGA}")
